{ "columns":0,
 "editorsettings":
    {
     "export":
        {
         "format":"tsx",
         "target":"..\/..\/Downloads\/level4..tsx"
        }
    },
 "grid":
    {
     "height":1,
     "orientation":"orthogonal",
     "width":1
    },
 "margin":0,
 "name":"level4",
 "spacing":0,
 "tilecount":26,
 "tiledversion":"1.3.0",
 "tileheight":128,
 "tiles":[
        {
         "id":0,
         "image":"..\/..\/Downloads\/brickGrey.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":1,
         "image":"..\/..\/Downloads\/planetHalf_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":2,
         "image":"..\/..\/Downloads\/waterTop_low (1).png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":3,
         "image":"..\/..\/Downloads\/water.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":4,
         "image":"..\/..\/Downloads\/planetCenter.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":5,
         "image":"..\/..\/Downloads\/rock (2).png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":6,
         "image":"..\/..\/Downloads\/planetMid.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":7,
         "image":"..\/..\/Downloads\/planetLeft (1).png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":8,
         "image":"..\/..\/Downloads\/planetRight.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":9,
         "image":"..\/..\/Downloads\/planetCorner_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":10,
         "image":"..\/..\/Downloads\/spikes.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":11,
         "image":"..\/..\/Downloads\/planetHalf_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":12,
         "image":"..\/..\/Downloads\/plantPurple.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":13,
         "image":"..\/..\/Downloads\/planetHalf_mid.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":14,
         "image":"..\/..\/Downloads\/doorClosed_mid.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":15,
         "image":"..\/..\/Downloads\/doorClosed_top.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":16,
         "image":"..\/..\/Downloads\/planetHill_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":17,
         "image":"..\/..\/Downloads\/planetHill_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":19,
         "image":"..\/..\/Downloads\/planetCliff_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":20,
         "image":"..\/..\/Downloads\/planetCliff_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":21,
         "image":"..\/..\/Downloads\/coinSilver (1).png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":22,
         "image":"..\/..\/Downloads\/planetCorner_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":23,
         "image":"..\/..\/Downloads\/planetCliffAlt_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":24,
         "image":"..\/..\/Downloads\/planetCliffAlt_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":25,
         "image":"..\/..\/Downloads\/ladderMid.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":26,
         "image":"..\/..\/Downloads\/ladderTop.png",
         "imageheight":128,
         "imagewidth":128
        }],
 "tilewidth":128,
 "type":"tileset",
 "version":1.2
}